---
title: "The Challenges"
---

+----+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| \# | Hole              | Par (3)                                                                           | Birdie (2)                                                                                                       | Hole-in-One (1)                                                                                                               |
+====+===================+===================================================================================+==================================================================================================================+===============================================================================================================================+
| 1  | Beantown Pub      | Any Sam Adams **OR** Start a toast!                                               | Win rocks paper scissors 3 times in a row                                                                        | Chug a Sam Adam's **OR answer this:** Name 9 players from the 2004 Red Sox.                                                   |
+----+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 2  | Sevens Ale House  | Craft Ale **OR**                                                                  | Name 3 notable Boston Sports players who wore jersey #7 or #77                                                   | Chug an Ale **OR answer this:**                                                                                               |
|    |                   |                                                                                   |                                                                                                                  |                                                                                                                               |
|    |                   | Cover someone else's drink                                                        |                                                                                                                  | What year did Prohibition End?                                                                                                |
+----+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 3  | 21st Amendment    | Cocktail **OR**                                                                   | After JFK was done partying at Harvard he dedicated his life to public service. What was the first move he made? | Another cocktail/mocktail **OR** Find an item or photo related to JFK and snap a pic                                          |
|    |                   |                                                                                   |                                                                                                                  |                                                                                                                               |
|    |                   | Mocktail                                                                          |                                                                                                                  |                                                                                                                               |
+----+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 4  | Hub Pub           | A local craft beer (Not Sam Adams) **OR answer this:**                            | List Boston’s championship years since 2000 (54% win rate), with teams.\                                         | Take a shot! **OR answer this:\                                                                                               |
|    |                   |                                                                                   | **OR\                                                                                                            | **Boston legalized weed in 2016. Burn one down.                                                                               |
|    |                   | List Boston’s championship years since 2000 (54% win rate), with teams.           | **Before 2001, when was the last time a Boston’s sports franchise won a world champions                          |                                                                                                                               |
+----+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 5  | Mr. Dooley's      | A pint of Guinness or an Irish Coffee or an Irish toast to the group              | Win a staring contest with a stranger.                                                                           | A pint of Guinness & a shot of whiskey **OR**                                                                                 |
|    |                   |                                                                                   |                                                                                                                  |                                                                                                                               |
|    |                   |                                                                                   |                                                                                                                  | What is the most popular and most imported whiskey in New England?                                                            |
+----+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 6  | Boston Sail Loft  | A Bud Light **OR** a Miller Lite **OR** a lemon lime Rickey                       | Find someone to arm wrestle with                                                                                 | Chug both a Bud Light **&** a Miller Lite **OR**                                                                              |
|    |                   |                                                                                   |                                                                                                                  |                                                                                                                               |
|    |                   |                                                                                   |                                                                                                                  | Chug soda water **& answer this:** What you'd name your boat if you had one.                                                  |
+----+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 7  | Black Rose        | A Guinness **OR** Irish pint, **OR** an Irish Lemonade (lemon, honey, soda water) | What is a symbol of Irish resistance to British rule?                                                            | Get a photo holding something from behind the bar.                                                                            |
+----+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 8  | Durty Nelly's     | A pint **OR** tell the group a funny story from your memory of Boston             | What's Durty Nelly's claim to fame?                                                                              | Finish a pint in 2 sips or less **OR** Name the district this bar is in. It has the oldest layout of colonial Boston streets. |
+----+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| 9  | The Dubliner      | That's a gimme                                                                    | That's a gimme                                                                                                   | Win the Guinness game **OR** A group photo (5 people or more)                                                                 |
+----+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
